services:
    post.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact', title: 'partial' } ]
        tags: [ 'api_platform.filter' ]
    post.boolean_filter:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments: [ { online: ~ } ]
        tags: [ 'api_platform.filter' ]
